const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '../.env');
const targetDir = path.join(__dirname, '../src/environments');
const targetPath = path.join(targetDir, 'environment.ts');

if (!fs.existsSync(envPath)) {
  console.error('.env file not found!');
  process.exit(1);
}

const envContent = fs.readFileSync(envPath, 'utf8');
const env = {};

envContent.split('\n').forEach(line => {
  const trimmedLine = line.trim();
  if (!trimmedLine || trimmedLine.startsWith('#')) {
    return;
  }
  const match = trimmedLine.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
  if (match) {
    let value = match[2] ? match[2].trim() : '';
    if (value.startsWith('"') && value.endsWith('"')) {
      value = value.substring(1, value.length - 1);
    } else if (value.startsWith("'") && value.endsWith("'")) {
      value = value.substring(1, value.length - 1);
    }
    env[match[1]] = value;
  }
});

// Ensure directory exists
if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

const content = `// This file is auto-generated by scripts/set-env.js
export const environment = {
  flightCircleClientId: '${env.FLIGHT_CIRCLE_CLIENT_ID || ""}',
  flightCircleClientSecret: '${env.FLIGHT_CIRCLE_CLIENT_SECRET || ""}',
  flightCircleRedirectUri: '${env.FLIGHT_CIRCLE_REDIRECT_URI || ""}',
  backendApiUrl: '${env.BACKEND_API_URL || ""}'
};
`;

fs.writeFileSync(targetPath, content, 'utf8');
console.log('Successfully generated environment.ts');
