name: Run tests and upload coverage report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests with Coverage
        run: npm run test -- --watch=false

      - name: Run tests with ViTest
        run: npx vitest run --coverage

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: VoeAviate/scheduler-frontend
