name: Run tests and upload coverage report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests with Coverage
        run: npm run test -- --watch=false

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          skip_validation: true
          slug: VoeAviate/scheduler-frontend
          verbose: true
